os: osx
osx_image: xcode10
language: node_js
node_js: '10'
jobs:
  include:
    - stage: release
      if: tag IS present
      before_deploy:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
      - yarn dist
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: Wu/wNNM5BuoIW3sXMxqg3C5cDdLAAQu3A9Ha8oQpJC7uRS2Xfd9uIHfLQp1j9Sr/znRiuYMcMjEwcQc5c3XsBP89dH5IIj/y4qkjlff2AtU2JC6vIgVAtQy/s3gM2OqzRIalnHqCV/IwdIBrlN/i/QywEzr3BDZhFx4wiRfksK3Ma7dCg3Io2ZwWQanDCmabxhBDVA/N2qNgjIvFJK/tZZ6BFP2q5VaurTcpBCARpMrkGYlBIiOr7Z+QRlQ7Yn6H6dBIGCoT4Hp8r+5cOA6cWBF3eb2z/j6MV2pnL7jGT3qdDAmXRXKrdR45MPwn53LWmuaqgaWKX+aNkynFnDUg5LTaLYGb/FGiXrDOuRU64SWKt3zfB9T0PITfzazTZRO7iVoYvE1onPZ1zXHiq7UMRyqkqNvn4m+jo3TAJudgHpRyodajKQHUoamXQVZMrFY+TsJOmO5AFg64WcUlh/F6/0mZce6U2UXghainCyymA8niYDFAtg8o9k1iUgSBszwEvH7rQHg9ZgK+koKHgV1moE0DSpESCjcFO5YvEfERxIlU4NPYnEDQo8T5aH0ZUJEC9StBJG5NWZWoiZd8PjLlgvAqBfhjT/cBaYCd/ugINvrKzsaGGHqxGNV6qRWbeyDjpM9Ycf1i5TfjslG97t3QHcL7HdLH1d2U7225l9KLwjo=
        keep_history: true
        file_glob: true
        file: dist/*
        on:
          tags: true
